language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
before_install:
  - sudo apt-get install gcc-4.9 g++-4.9 cpp-4.9
  # Bazel hardcodes /usr/bin/gcc by default :s
  # https://github.com/bazelbuild/bazel/issues/649, https://github.com/tensorflow/tensorflow/issues/336 FML
  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++
  - sudo rm /usr/bin/cpp
  - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo ln -s /usr/bin/cpp-4.9 /usr/bin/cpp
  - /usr/bin/gcc --version

  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - echo "startup --host_jvm_args=-Xmx2500m" >> .bazelrc
  - echo "startup --host_jvm_args=-Xms2500m" >> .bazelrc
  - echo "test --ram_utilization_factor=10" >> .bazelrc
  - echo "startup --batch" >> .bazelrc
  - echo "build --spawn_strategy=standalone --genrule_strategy=standalone --jobs 10 --local_resources 2048,.5,1.0" >> .bazelrc
  - export BAZELRC="$(pwd)/.bazelrc"

  # BAZEL
  # Based on https://github.com/korfuri/bazel-travis
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.4/bazel-0.1.4-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.4-installer-linux-x86_64.sh
  - ./bazel-0.1.4-installer-linux-x86_64.sh --user
  - cat ~/.bazelrc >> .bazelrc
  
install:
#  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0rc0-cp27-none-linux_x86_64.whl
#  - pip install -r requirements.txt
# command to run tests
script: tests
